package failure

// Code identifies one stable, machine-readable failure condition.
type Code string

const (
	CodeInternalError Code = "INTERNAL_ERROR"

	CodeOperationUnsupported                  Code = "OPERATION_UNSUPPORTED"
	CodeOperationCanceled                     Code = "OPERATION_CANCELED"
	CodeOperationTimeout                      Code = "OPERATION_TIMEOUT"
	CodeVerificationFlowUnsupported           Code = "VERIFICATION_FLOW_UNSUPPORTED"
	CodeInteractionHandlerRequired            Code = "INTERACTION_HANDLER_REQUIRED"
	CodeInteractionCanceled                   Code = "INTERACTION_CANCELED"
	CodeAuthenticatorClosed                   Code = "AUTHENTICATOR_CLOSED"
	CodeDeviceNotFound                        Code = "DEVICE_NOT_FOUND"
	CodeTransportModeUnsupported              Code = "TRANSPORT_MODE_UNSUPPORTED"
	CodeTransportPermissionDenied             Code = "TRANSPORT_PERMISSION_DENIED"
	CodeTransportProxyUnavailable             Code = "TRANSPORT_PROXY_UNAVAILABLE"
	CodeTransportFailure                      Code = "TRANSPORT_FAILURE"
	CodeMDSAAGUIDInvalid                      Code = "MDS_AAGUID_INVALID"
	CodeMDSFetchFailed                        Code = "MDS_FETCH_FAILED"
	CodeMDSVerificationFailed                 Code = "MDS_VERIFICATION_FAILED"
	CodeRelyingPartyIDRequired                Code = "RELYING_PARTY_ID_REQUIRED"
	CodeUserIDRequired                        Code = "USER_ID_REQUIRED"
	CodeClientDataJSONRequired                Code = "CLIENT_DATA_JSON_REQUIRED"
	CodePublicKeyCredentialParametersRequired Code = "PUBLIC_KEY_CREDENTIAL_PARAMETERS_REQUIRED"
	CodePublicKeyCredentialAlgorithmRequired  Code = "PUBLIC_KEY_CREDENTIAL_ALGORITHM_REQUIRED"
	CodeCredentialIDRequired                  Code = "CREDENTIAL_ID_REQUIRED"
	CodeCredentialNotFound                    Code = "CREDENTIAL_NOT_FOUND"
	CodeCredentialExcluded                    Code = "CREDENTIAL_EXCLUDED"
	CodeCredentialStoreFull                   Code = "CREDENTIAL_STORE_FULL"
	CodeCredentialManagementUnsupported       Code = "CREDENTIAL_MANAGEMENT_UNSUPPORTED"
	CodeCredentialChangesRequired             Code = "CREDENTIAL_CHANGES_REQUIRED"
	CodeUserIDHexInvalid                      Code = "USER_ID_HEX_INVALID"
	CodeAttestedCredentialDataMissing         Code = "ATTESTED_CREDENTIAL_DATA_MISSING"
	CodeCredentialCreationDenied              Code = "CREDENTIAL_CREATION_DENIED"
	CodeAssertionDenied                       Code = "ASSERTION_DENIED"
	CodeAssertionNotAllowed                   Code = "ASSERTION_NOT_ALLOWED"
	CodeAssertionContinuationUnavailable      Code = "ASSERTION_CONTINUATION_UNAVAILABLE"

	CodePINUnsupported              Code = "PIN_UNSUPPORTED"
	CodePINAlreadyConfigured        Code = "PIN_ALREADY_CONFIGURED"
	CodePINNotConfigured            Code = "PIN_NOT_CONFIGURED"
	CodePINRequired                 Code = "PIN_REQUIRED"
	CodePINInvalid                  Code = "PIN_INVALID"
	CodePINBlocked                  Code = "PIN_BLOCKED"
	CodePINUVAuthInvalid            Code = "PIN_UV_AUTH_INVALID"
	CodePINUVAuthBlocked            Code = "PIN_UV_AUTH_BLOCKED"
	CodePINPolicyViolation          Code = "PIN_POLICY_VIOLATION"
	CodePINChangeRequired           Code = "PIN_CHANGE_REQUIRED"
	CodePINUVAuthTokenRequired      Code = "PIN_UV_AUTH_TOKEN_REQUIRED"
	CodePINUVPermissionUnauthorized Code = "PIN_UV_PERMISSION_UNAUTHORIZED"
	CodeUserPresenceRequired        Code = "USER_PRESENCE_REQUIRED"
	CodeUserVerificationBlocked     Code = "USER_VERIFICATION_BLOCKED"
	CodeUserVerificationInvalid     Code = "USER_VERIFICATION_INVALID"

	CodeBioUnsupported                   Code = "BIO_UNSUPPORTED"
	CodeBioTemplateIDRequired            Code = "BIO_TEMPLATE_ID_REQUIRED"
	CodeBioTemplateIDInvalid             Code = "BIO_TEMPLATE_ID_INVALID"
	CodeBioNoEnrollments                 Code = "BIO_NO_ENROLLMENTS"
	CodeBioEnrollmentNotFound            Code = "BIO_ENROLLMENT_NOT_FOUND"
	CodeBioDatabaseFull                  Code = "BIO_DATABASE_FULL"
	CodeAuthenticatorConfigUnsupported   Code = "AUTHENTICATOR_CONFIG_UNSUPPORTED"
	CodeAuthenticatorConfigStorageFull   Code = "AUTHENTICATOR_CONFIG_STORAGE_FULL"
	CodeAuthenticatorOperationDenied     Code = "AUTHENTICATOR_OPERATION_DENIED"
	CodeAuthenticatorOperationNotAllowed Code = "AUTHENTICATOR_OPERATION_NOT_ALLOWED"
	CodeAlwaysUVStateUnknown             Code = "ALWAYS_UV_STATE_UNKNOWN"
	CodeAlwaysUVAlreadyTarget            Code = "ALWAYS_UV_ALREADY_TARGET"
	CodeMinPINLengthUnsupported          Code = "MIN_PIN_LENGTH_UNSUPPORTED"
	CodeMinPINLengthDecreaseNotAllowed   Code = "MIN_PIN_LENGTH_DECREASE_NOT_ALLOWED"
	CodeResetWindowExpired               Code = "RESET_WINDOW_EXPIRED"
	CodeResetTouchTimeout                Code = "RESET_TOUCH_TIMEOUT"

	CodeLargeBlobUnsupported           Code = "LARGE_BLOB_UNSUPPORTED"
	CodeLargeBlobKeyMissing            Code = "LARGE_BLOB_KEY_MISSING"
	CodeLargeBlobKeyInvalid            Code = "LARGE_BLOB_KEY_INVALID"
	CodeLargeBlobArrayTooLarge         Code = "LARGE_BLOB_ARRAY_TOO_LARGE"
	CodeLargeBlobStorageFull           Code = "LARGE_BLOB_STORAGE_FULL"
	CodeLargeBlobArrayInvalid          Code = "LARGE_BLOB_ARRAY_INVALID"
	CodeLargeBlobWriteSequenceInvalid  Code = "LARGE_BLOB_WRITE_SEQUENCE_INVALID"
	CodeLargeBlobIntegrityFailure      Code = "LARGE_BLOB_INTEGRITY_FAILURE"
	CodeLargeBlobUTF8Invalid           Code = "LARGE_BLOB_UTF8_INVALID"
	CodeLargeBlobJSONInvalid           Code = "LARGE_BLOB_JSON_INVALID"
	CodeLargeBlobCBORInvalid           Code = "LARGE_BLOB_CBOR_INVALID"
	CodeLargeBlobDecodeModeUnsupported Code = "LARGE_BLOB_DECODE_MODE_UNSUPPORTED"

	CodeCTAPCommandInvalid             Code = "CTAP_COMMAND_INVALID"
	CodeCTAPParameterInvalid           Code = "CTAP_PARAMETER_INVALID"
	CodeCTAPLengthInvalid              Code = "CTAP_LENGTH_INVALID"
	CodeCTAPSequenceInvalid            Code = "CTAP_SEQUENCE_INVALID"
	CodeAuthenticatorTimeout           Code = "AUTHENTICATOR_TIMEOUT"
	CodeAuthenticatorBusy              Code = "AUTHENTICATOR_BUSY"
	CodeCTAPLockRequired               Code = "CTAP_LOCK_REQUIRED"
	CodeCTAPChannelInvalid             Code = "CTAP_CHANNEL_INVALID"
	CodeCTAPCBORTypeInvalid            Code = "CTAP_CBOR_TYPE_INVALID"
	CodeCTAPCBORInvalid                Code = "CTAP_CBOR_INVALID"
	CodeCTAPSpecViolation              Code = "CTAP_SPEC_VIOLATION"
	CodeCTAPParameterMissing           Code = "CTAP_PARAMETER_MISSING"
	CodeCTAPLimitExceeded              Code = "CTAP_LIMIT_EXCEEDED"
	CodeAuthenticatorProcessing        Code = "AUTHENTICATOR_PROCESSING"
	CodeCredentialInvalid              Code = "CREDENTIAL_INVALID"
	CodeUserActionPending              Code = "USER_ACTION_PENDING"
	CodeAuthenticatorOperationPending  Code = "AUTHENTICATOR_OPERATION_PENDING"
	CodeAuthenticatorNoOperations      Code = "AUTHENTICATOR_NO_OPERATIONS"
	CodeAlgorithmUnsupported           Code = "ALGORITHM_UNSUPPORTED"
	CodeCTAPOptionUnsupported          Code = "CTAP_OPTION_UNSUPPORTED"
	CodeCTAPOptionInvalid              Code = "CTAP_OPTION_INVALID"
	CodeAuthenticatorOperationCanceled Code = "AUTHENTICATOR_OPERATION_CANCELED"
	CodeUserActionTimeout              Code = "USER_ACTION_TIMEOUT"
	CodeCTAPRequestTooLarge            Code = "CTAP_REQUEST_TOO_LARGE"
	CodeAuthenticatorActionTimeout     Code = "AUTHENTICATOR_ACTION_TIMEOUT"
	CodeCTAPIntegrityFailure           Code = "CTAP_INTEGRITY_FAILURE"
	CodeCTAPSubcommandInvalid          Code = "CTAP_SUBCOMMAND_INVALID"
	CodeCTAPOtherError                 Code = "CTAP_OTHER_ERROR"
	CodeCTAPReservedStatus             Code = "CTAP_RESERVED_STATUS"
	CodeCTAPExtensionError             Code = "CTAP_EXTENSION_ERROR"
	CodeCTAPVendorError                Code = "CTAP_VENDOR_ERROR"
	CodeGetInfoUnsupported             Code = "GET_INFO_UNSUPPORTED"
	CodeAuthenticatorSelectionTimeout  Code = "AUTHENTICATOR_SELECTION_TIMEOUT"
	CodeAuthenticatorSelectionCanceled Code = "AUTHENTICATOR_SELECTION_CANCELED"
	CodeBioInteractionTimeout          Code = "BIO_INTERACTION_TIMEOUT"
)

// Category groups failure codes for coarse recovery behavior.
type Category string

const (
	CategoryUnsupported      Category = "unsupported"
	CategoryPermissionDenied Category = "permission-denied"
	CategoryTransportFailure Category = "transport-failure"
	CategoryTimeout          Category = "timeout"
	CategoryBusy             Category = "busy"
	CategoryInvalidOperation Category = "invalid-operation"
	CategoryInvalidState     Category = "invalid-state"
	CategoryCanceled         Category = "canceled"
	CategoryInternal         Category = "internal"
)

// Phase identifies the runtime phase in which a failure occurred.
type Phase string

const (
	PhaseValidation            Phase = "validation"
	PhaseDiscovery             Phase = "discovery"
	PhaseAuthenticator         Phase = "authenticator"
	PhaseInteraction           Phase = "interaction"
	PhaseTokenAcquisition      Phase = "token-acquisition"
	PhaseAuthenticatorCommand  Phase = "authenticator-command"
	PhaseAssertionContinuation Phase = "assertion-continuation"
	PhaseMetadata              Phase = "metadata"
	PhaseIdentity              Phase = "identity"
	PhaseDecode                Phase = "decode"
	PhaseCleanup               Phase = "cleanup"
)
